Fix 3rd party keyboards obscure the seed input on Welcome
nano-wallet-company/nano-wallet-ios pull request #24
Opened 2018-07-23 22:22 UTC by tiagocanto01

2018-07-24 00:09 UTC, tiagocanto01 commented
![video](https://user-images.githubusercontent.com/7191194/43109308-8cbdd6fe-8ebc-11e8-98f4-e15d656d2d2f.gif)

2019-04-06 23:25 UTC, bibobode requested changes

2019-04-06 23:25 UTC, bibobode commented on Raiblocks/New User Experience/WelcomeViewController.swift
> +        let keyboardHeight = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).cgRectValue.height
Hmm.. not sure if I like the force cast here :)

2020-10-12 15:31 UTC, zhyatt commented
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.

2020-10-12 15:31 UTC, closed without merging